In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('customer-recipes.csv')
data.head(10)

,Customer Code,First Name,Last Name,Email,Job Title,Recipe,Recipe Score,Location
0,JL9123,Elliot,King,elliotking@gmail.com,Data Scientist,Leftover Burrito,4,New York
1,JL8152,Noel,Hall,noelhall@gmail.com,UX Researcher,Eggs in a Nest,7,Texas
2,JL8315,Robert,Wright,robertwright@gmail.com,Data Scientist,Loaded Tater Tots,9,Washington
3,JL8753,Addison,Lee,addisonlee@gmail.com,Senior Data Scientist,Green Onion Pancakes,8,New York
4,JL7123,Bobby,Gray,bobbygray@gmail.com,Software Engineer,Lamb Chops with Mint Jelly,9,California
5,JL0961,Gordon,Hamsay,gordonhamsay@gmail.com,UX/UI Designer,Beef Wellington,10,California
6,JL7812,Guy,Mustang,guymustang@gmail.com,Sales Manager,Flavortown French Toast,10,California
7,JL8715,Abed,Glover,abed.glover@gmail.com,UX Researcher,Buttered Noodles,7,Florida
8,JL8018,Avery,Malone,amalone@gmail.com,Data Scientist,Peanut Butter Protein Shake,5,Oregon
9,JL3761,Taylor,Zhou,taylor_zhou@gmail.com,Sales Manager,Fluffy Pancakes,8,Hawaii